### ISSUE TITLE
关于静态网页的一些疑惑

### ISSUE THREAD

**Issue by einverne** [fanpaiyingping/fanpaiyingping.github.io#1]
看到反派影评的地址过来看了一下，网站的源码大部分都是以静态页面的形式提交的，有个疑惑 Hexo 的网站 GitHub 本来就支持托管，为什么不使用源码的形式提交。这样带来的一些坏处

- 每改动一处，可能需要提交的内容会非常多，每个页面都需要更新，不适合查看改动，如果以后更新多的话，非常不适合维护
- 另外也不利于将主题单独修改贡献出来，以前有个 podcast 的项目 https: //github.com/einverne/podcast ，可以参考，如果使用源码的方式提交，那么每一次修改，或者每一次更新都能非常清晰的看到提交，也方便别人修正代码中的问题，如果有需要也可以参与到主题的制作，或者自动化的发布中
- 另外就是静态网页非常不方便的地方就是后台管理，如果没有方便的后台管理，对于更新发布来说是个灾难。

当然我也理解不使用源码发布的理由，如果是因为版权，或者抄袭的问题的话，那就没有办法了。

**Comment by fanpaiyingping** [comment]
谢谢你的留言！ 不好意思现在才看到。
不使用源码发布的最根本原因是我不知道还可以这样哈哈哈！

不过因为反派影评根本没有多余人手，整个网站也都是还有我一个人在业余时间在管理，所以上传源码大家合作的机会目前不多。由于每次改动也都是我来做，所以也不会很困惑，但是不专业确实是肯定的啦。 应该会之后有空按你说的改成上传源码！

对于网站这些我完全是门外汉，目前的后台管理确实头疼的要死。我已经尽量把大部分内容放到了最后自动生成的代码中，但是还是每篇文章的内容修改及其麻烦。不知道你有什么别的方法推荐呢？ 

如果你不介意的话可以发邮件联系～ 这样比较方便一点～ siyuan@fanpiefilm.com
谢谢！！！！

**Comment by fanpaiyingping** [comment]
谢谢你的留言！ 不好意思现在才看到。
不使用源码发布的最根本原因是我不知道还可以这样哈哈哈！

不过因为反派影评根本没有多余人手，整个网站也都是还有我一个人在业余时间在管理，所以上传源码大家合作的机会目前不多。由于每次改动也都是我来做，版本控制的困惑倒是还好，但是不专业确实是肯定的啦。 应该会之后有空按你说的改成上传源码！

对于网站这些我完全是门外汉，目前的后台管理确实头疼的要死。我已经尽量把大部分内容放到了最后自动生成的代码中，但是还是每篇文章的内容修改及其麻烦。不知道你有什么别的方法推荐呢？

如果你不介意的话可以发邮件联系～ 这样比较方便一点～ siyuan@fanpiefilm.com
谢谢！！！！

**Comment by YuduanPu** [comment]
反派影评，每周更新lol
